library/urls.py
from django.conf.urls import url,include
from django.contrib.staticfiles import views
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('management.urls')),
]

urlpatterns+=[
        url(r'^static/(?P<path>.*)$',views.static.serve,{'document_root':settings.STATIC_ROOT},name='static'),
        url(r'^media/(?P<path>.*)$',views.static.serve,{'document_root':settings.MEDIA_ROOT},name='media'),
    ]

management/urls.py
from django.conf.urls import url
from management import views

urlpatterns=[
        url(r'^$',views.index,name='homepage'),
        url(r'^signup/$',views.signup,name='signup'),
        url(r'^login/$',views.login,name='login'),
        url(r'^logout/$',views.logout,name='logout'),
        url(r'^set_password/$',views.set_password,name='set_password'),
        url(r'^add_book/$',views.add_book,name='add_book'),
        url(r'^view_book_list/$',views.view_book_list,name='view_book_list'),
        url(r'^detail/$',views.detail,name='detail'),
        url(r'^add_img/$',views.add_img,name='add_img'),
        url(r'^add_pdf/$',views.add_pdf,name='add_pdf'),
        url(r'^view_pdf/$',views.view_pdf,name='view_pdf'),
        url(r'^import_book/$',views.import_book,name='import_book'),
        url(r'^import_info/$',views.import_info,name='import_info'),
        ]

management/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class MyUser(models.Model):
    user=models.OneToOneField(User)
    nickname=models.CharField(max_length=16)
    permission=models.IntegerField(default=1)

    def __unicode__(self):
        return self.user.username



class Book(models.Model):
    name=models.CharField(max_length=128)
    price=models.FloatField()
    author=models.CharField(max_length=128)
    publish_date=models.DateField()
    category=models.CharField(max_length=128)
    summary=models.TextField(default="a book")

    class META:
        ordering=['name']

    def __unicode__(self):
        return self.name

class Img(models.Model):
    name=models.CharField(max_length=128)
    description=models.TextField()
    img=models.ImageField(upload_to='image/%Y/%m/%d')
    book=models.ForeignKey(Book)

    class META:
        ordering=['name']
    def __unicode__(self):
        return self.name


class Pdf(models.Model):
    name=models.CharField(max_length=128)
    descriptions=models.TextField()
    pdf=models.FileField(upload_to='pdf')
    book=models.OneToOneField(Book)

    class META:
        ordering=['name']

    def __unicode__(self):
        return self.name

management/views.py
#!/usr/bin python
#-*- coding:utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import user_passes_test,login_required
from django.contrib.auth.models import User
from django.contrib import auth
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from management.models import MyUser,Book,Img,Pdf
from django.core.urlresolvers import reverse
from management.utils import permission_check
import os
import magic
from management.douban import book_search

import urllib
from io import BytesIO
from django.core.files import File

# Create your views here.
def index(request):
    user=request.user if request.user.is_authenticated() else None
    content={
            'active_menu':'homepage',
            'user':user,
            }
    return render(request,'management/index.html',content)

def signup(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('homepage'))
    state=None
    if request.method=='POST':
        password=request.POST.get('password','')
        repeat_password=request.POST.get('repeat_password','')
        if password == '' or repeat_password=='':
            state='empty'
        elif password!=repeat_password:
            state='repeat_error'
        else:
            username=request.POST.get('username','')
            if User.objects.filter(username=username):
                state='user_exist'
            else:
                new_user=User.objects.create_user(username=username,password=password,email=request.POST.get('email',''))
                new_user.save()
                new_my_user=MyUser(user=new_user,nickname=request.POST.get('nickname',''))
                new_my_user.save()
                state='success'
    content={
                'active_menu':'homepage',
                'state':state,
                'user':None,
                }
    return render(request,'management/signup.html',content)


def login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('homepage'))
    state=None
    if request.method=='POST':
        username=request.POST.get('username','')
        password=request.POST.get('password','')
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return HttpResponseRedirect(reverse('homepage'))
        else:
            state='not_exist_or_password_error'

    content={
            'active_menu':'homepage',
            'state':state,
            'user':None,
            }
    return render(request,'management/login.html',content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('homepage'))


@login_required
def set_password(request):
    user=request.user
    state=None
    if request.method=='POST':
        old_password=request.POST.get('old_password','')
        new_password=request.POST.get('new_password','')
        repeat_password=request.POST.get('repeat_password','')
        if user.check_password(old_password):
            if not new_password:
                state='empty'
            elif new_password!=repeat_password:
                state='repeat_error'
            else:
                user.set_password(new_password)
                user.save()
                state='success'
        else:
            state='password_error'

    content={
            'user':user,
            'active_menu':'homepage',
            'state':state,
            }
    return render(request,'management/set_password.html',content)


@user_passes_test(permission_check)
def add_book(request):
    user=request.user
    state=None
    if request.method=='POST':
        new_book=Book(
                name=request.POST.get('name',''),
                author=request.POST.get('author',''),
                category=request.POST.get('category',''),
                price=request.POST.get('price',0),
                publish_date=request.POST.get('publish_date',''),
                summary=request.POST.get('summary','')
                )
        new_book.save()
        state='success'

    content={
                'user':user,
                'active_menu':'add_book',
                'state':state,
            }
    return render(request,'management/add_book.html',content)


def view_book_list(request):
    user=request.user if request.user.is_authenticated() else None
    category_list=Book.objects.values_list('category',flat=True).distinct()
    query_category=request.GET.get('category','all')
    if(not query_category) or Book.objects.filter(category=query_category).count() is 0:
        query_category = 'all'
        book_list=Book.objects.all()
    else:
        book_list=Book.objects.filter(category=query_category)

    if request.method=='POST':
        keyword=request.POST.get('keyword','')
        book_list=Book.objects.filter(name__contains=keyword)
        query_category='all'

    paginator=Paginator(book_list,15)
    page=request.GET.get('page')
    try:
        book_list=paginator.page(page)
    except PageNotAnInteger:
        book_list=paginator.page(1)
    except EmptyPage:
        book_list=paginator.page(paginator.num_pages)


    content={
            'user':user,
            'active_menu':'view_book',
            'category_list':category_list,
            'query_category':query_category,
            'book_list':book_list,
            }
    return render(request,'management/view_book_list.html',content)

def detail(request):
    user=request.user if request.user.is_authenticated() else None
    book_id=request.GET.get('id','')
    if book_id=='':
        return HttpResponseRedirect(reverse('view_book_list'))
    try:
        book=Book.objects.get(pk=book_id)
    except Book.DoesNotExist:
        return HttpResponseRedirect(reverse('view_book_list'))

    content={
            'user':user,
            'active_menu':'view_book',
            'book':book,
            }
    return render(request,'management/detail.html',content)


@user_passes_test(permission_check)
def add_img(request):
    user=request.user
    state=None
    if request.method=='POST':
        try:
            new_img=Img(
                    name=request.POST.get('name',''),
                    description=request.POST.get('description',''),
                    img=request.FILES.get('img',''),
                    book=Book.objects.get(id=request.POST.get('book',''))
                    )
            new_img.save()
        except Book.DoesNotExist as e:
            state='error'
            print(e)
        else:
            state='success'


    content={
            'user':user,
            'state':state,
            'book_list':Book.objects.all(),
            'active_menu':'add_img',
            }
    return render(request,'management/add_img.html',content)

@user_passes_test(permission_check)
def add_pdf(request):
    user=request.user
    state=None
    if request.method=='POST':
        try:
            new_pdf=Pdf(
                    name=request.POST.get('name',''),
                    descriptions=request.POST.get('description',''),
                    pdf=request.FILES.get('pdf',''),
                    book=Book.objects.get(id=request.POST.get('book',''))
                    )
            new_pdf.save()
        except Book.DoesNotExist as e:
            state='error'
            print(e)
        else:
            state=judgeAndTransform(new_pdf)
            #state='success'

    content={
            'user':user,
            'state':state,
            'book_list':Book.objects.all(),
            'active_menu':'add_pdf',
            }
    return render(request,'management/add_pdf.html',content)

def view_pdf(request):
    user=request.user if request.user.is_authenticated() else None
    book_id=request.GET.get('id','')
    if book_id=='':
        return HttpResponseRedirect(reverse('view_book_list'))
    try:
        book=Book.objects.get(pk=book_id)
        pdf=Pdf.objects.get(book=book)
    except Book.DoesNotExist:
        return HttpResponseRedirect(reverse('view_book_list'))
    except Pdf.DoesNotExist:
        return HttpResponseRedirect(reverse('view_book_list'))

    content={
            'user':user,
            'active_menu':'view_pdf',
            'pdf':pdf,
            }
    return render(request,'management/view_pdf.html',content)

@user_passes_test(permission_check)
def import_book(request):
    user=request.user if request.user.is_authenticated() else None
    list_search=[]
    jud=0
    if request.method=='POST':
        query_name=request.POST.get('query_search','')
        query_name=query_name.encode("utf-8")
        list_search=book_search(query_name)
        jud=1
    content={
            'user':user,
            'active_menu':'import_book',
            'list_search':list_search,
            'jud':jud
            }
    return render(request,'management/import_book.html',content)

@user_passes_test(permission_check)
def import_info(request):
    user=request.user if request.user.is_authenticated() else None
    state=None
    if request.method=='POST':
        books=request.POST.getlist('search','')
        for book in books:
            book=eval(book)
            book_name=book['title']
            book_author=book['author']
            book_price=book['price']
            book_pubdate=book['pubdate']
            book_sum=book['summary']
            if book['category']:
                book_category=book['category']
            else:
                book_category=u'导入图书'
            try:
                new_book=Book(
                        name=book_name,
                        author=book_author,
                        price=book_price,
                        category=book_category,
                        publish_date=book_pubdate,
                        summary=book_sum
                        )
                new_book.save()

management/templates/management/add_book.html
{% extends "management/base.html" %}
{% load staticfiles %}
{% block title %}添加图书{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
				{% if state == 'success' %}
				<div class="well">
					<h2 class="text-success text-center">添加成功</h2>
				</div>
				<ul class="pager">
					<li class="previous"><a class="text-left" href="{% url 'add_book' %}">继续添加</a></li>
					<li class="next"><a class="text-right" href="{% url 'homepage' %}">回到主页</a></li>
				</ul>

				{% else %}
				<form method="POST" role="form" class="form-horizontal">
					{% csrf_token %}
					<h1 class="form-signin-heading text-center">添加图书</h1>

					<div class="form-group">
						<label for="id_name" class="col-md-3 control-label">书名：</label>
						<div class="col-md-9">
							<input type="text" class="form-control" id="id_name" required name="name" autofocus>
						</div>
					</div>


					<div class="form-group">
						<label for="id_author" class="col-md-3 control-label">作者：</label>
						<div class="col-md-9">
							<input type="text" class="form-control" id="id_author" required name="author" autofocus>
						</div>
					</div>
					
					<div class="form-group">
						<label for="id_category" class="col-md-3 control-label">类型：</label>
						<div class="col-md-9">
							<input type="text" class="form-control" id="id_category" required name="category" autofocus>
						</div>
					</div>

					<div class="form-group">
						<label for="id_price" class="col-md-3 control-label">价格：</label>
						<div class="col-md-9">
							<input type="text" class="form-control" id="id_price" required name="price" autofocus>
						</div>
					</div>

					<div class="form-group">
						<label for="id_pubdate" class="col-md-3 control-label">出版日期：</label>
						<div class="col-md-9">
							<input type="date" class="form-control" id="id_pubdate" required name="publish_date" autofocus>
						</div>
					</div>

					<div class="form-group">
						<label for="id_summary" class="col-md-3 control-label">描述：</label>
						<div class="col-md-9">
							<textarea class="form-control" id="id_summary" required name="summary" rows="4" autofocus></textarea>
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-4 col-md-offset-8">
							<button class="btn btn btn-primary btn-block" type="submit">提交</button>
						</div>
					</div>
				</form>

				<div class="col-md-4 col-md-offset-8">
					<ul class="pager">
						<li class="next"><a class="text-center" href="{% url 'import_book' %}">点这里导入图书</a></li>
					</ul>
				</div>
				
				{% endif %}
			</div>
		</div>
	</div>

{% endblock %}

management/templates/management/add_img.html
{% extends "management/base.html" %}
{% block title %}添加图片{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
			{% if state == 'success' %}
			<div class="well">
				<h2 class="text-success text-center">添加成功</h2>
			</div>
			{% elif state == 'error' %}
			<div class="well">
				<h2 class="text-danger text-center">添加失败</h2>
			</div>
			{% endif %}
			<form method="POST" role="form" class="form-horizontal" enctype="multipart/form-data">
				{% csrf_token %}
				<h1 class="form-signin-heading text-center">添加图片</h1>

				<div class="form-group">
					<label for="id_name" class="col-md-3 control-label">名称：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" id="id_name" required name="name" autofocus>
					</div>
				</div>

				<div class="form-group">
					<label for="id_description" class="col-md-3 control-label">描述：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" id="id_description" required name="description" autofocus>
					</div>
				</div>

				<div class="form-group">
					<label for="id_book" class="col-md-3 control-label">所属书籍：</label>
					<div class="col-md-9">
						<select name="book" id="id_book" class="form-control">
							{%for book in book_list %}
							<option value="{{ book.id }}">{{ book.name }}</option>
							{% endfor %}
						</select>
					</div>
				</div>


				<div class="form-group">
					<label for="id_img" class="col-md-3 control-label">图片：</label>
					<div class="col-md-9">
						<input type="file" class="form-control" id="id_img" required name="img">
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-4 col-md-offset-4">
						<button class="btn btn btn-primary btn-block" type="submit">提交</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

management/templates/management/add_pdf.html
{% extends "management/base.html" %}
{% block title %}添加PDF{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
			{% if state == 'success' %}
			<div class="well">
				<h2 class="text-success text-center">添加成功</h2>
			</div>
			{% elif state == 'error' %}
			<div class="well">
				<h2 class="text-danger text-center">添加失败</h2>
			</div>
			{% endif %}

			<form method="POST" role="form" class="form-horizontal" enctype="multipart/form-data">
				{% csrf_token %}
				<h1 class="form-signin-heading text-center">添加PDF</h1>
				<div class="form-group">
					<label for="id_name" class="col-md-3 control-label">名称：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" id="id_name" required name="name" autofocus>
					</div>
				</div>
				<div class="form-group">
					<label for="id_description" class="col-md-3 control-label">描述：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" id="id_description" required name="description" autofocus>
					</div>
				</div>

				<div class="form-group">
					<label for="id_book" class="col-md-3 control-label">所属书籍：</label>
					<div class="col-md-9">
						<select name="book"  id="id_book" class="form-control">
							{% for book in book_list %}
							<option value="{{ book.id }}">{{ book.name }}</option>
							{% endfor %}
						</select>
					</div>
				</div>
				<div class="form-group">
					<label for="id_pdf" class="col-md-3 control-label">PDF：</label>
					<div class="col-md-9">
						<input type="file" class="form-control" id="id_pdf" required name="pdf" autofocus>
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-4 col-md-offset-4">
						<button class="btn btn btn-primary btn-block" type="submit">提交</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

management/templates/management/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'management/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'management/css/bootstrap-theme.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'management/css/base.css' %}">
	<script type="text/javascript" src="{% static 'management/js/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'management/js/bootstrap.min.js' %}"></script>
</head>
<body style="padding-bottom:70px;">
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-basepage">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a href="{% url 'homepage' %}" class="navbar-brand">Library</a>
			</div>

			<div class="collapse navbar-collapse" id="navbar-collapse-basepage">
				<ul class="nav navbar-nav">
					<li id="homepage"><a href="{% url 'homepage' %}">主页</a></li>
					{% if user.myuser.permission > 1 %}
					<li id="add_book"><a href="{% url 'add_book' %}">添加图书</a></li>
					<li id="add_img"><a href="{% url 'add_img' %}">添加图片</a></li>
					<li id="add_pdf"><a href="{% url 'add_pdf' %}">添加PDF</a></li>
					{% endif %}
					<li id="view_book"><a href="{% url 'view_book_list' %}">查看图书</a></li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					{% if user %}
					<li><p class="navbar-text">欢迎您&nbsp;&nbsp;<span id="base_name">{{ user.myuser.nickname }}</span></p></li>
					<li><a href="{% url 'logout' %}">注销</a></li>
					<li><a href="{% url 'set_password' %}">修改密码</a></li>
					{% else %}
					<li><a href="{% url 'signup' %}">注册</a></li>
					<li><a href="{% url 'login' %}">登陆</a></li>
					{% endif %}

			</div>
		</div>
	</nav>
	
	<header class="jumbotron subhead" id="header-base">
		<div class="container">
			<h1 class="text-center">图书管理系统</h1>
			<h3 class="text-center">——知识改变命运</h3>
		</div>
	</header>


	{% block content %}{% endblock %}
	


<footer class="footer navbar-fixed-bottom">
<div class="container">
	<p class="text-muted text-center credit"><strong>HIT-CS</strong></p>
	<p class="text-muted text-center credit">@ALL rights reserved</p>
</div>
</footer>
<script type="text/javascript">
	$('#{{ active_menu }}').addClass("active");
</script>
</body>
</html>

management/templates/management/detail.html
{% extends "management/base.html" %}
{% load staticfiles %}

{% block title %}查看图书{% endblock %}

{% block content %}

<div class="container">
	<div class "row">
		<div class="col-md-10 col-md-offset-1">
			<div class="col-md-4">
				{% if book.img_set.all %}
				<div id="carousel-generic" class="carousel slide" data-ride="carousel">
					<ol class="carousel-indicators">
						{% for img in book.img_set.all %}
						<li data-target="#carousel-generic" data-slide-to="{{ forloopcounter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
						{% endfor %}
					</ol>

					<div class="carousel-inner" role="listbox">
						{% for img in book.img_set.all %}
						<div {% if forloop.first %}class="item active"{% else %}class="item"{% endif %}>
							<img class="img-rounded" src="{% url 'media' img.img %}"> 
						</div>
						{% endfor %}
					</div>

					<a class="left carousel-control" href="#carousel-generic" role="button" data-slide="prev">
						<span class="glyphicon glyphicon-chevron-left"></span></a>
					<a class="right carousel-control" href="#carousel-generic" role="button" data-slide="next">
						<span class="glyphicon glyphicon-chevron-right"></span></a>

				</div>
				{% else %}
				<p class="text-center">暂无图片</p>
				{% endif %}

			</div> 


			<div class="col-md-12">
				<h2 >{{ book.name }}</h2>
				<h4>作者：{{ book.author }}</h3>
				<h4>类别：{{ book.category }}</h3>
				<h4>出版日期：{{ book.publish_date|date:"Y-m-d" }}</h3>
				<h4>价格：{{ book.price|floatformat:2 }}</h3>
				<h4>介绍：</h4>
				<section>
				<div class="col-md-12" style="background-color: #f5ffe8;
               box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;">
				<p class="text-justify">{{ book.summary }}</p>
				</div>
				</section>
			</div>
		</div>
	</div>
</div>
{% endblock %}

management/templates/management/import_book.html
{% extends "management/base.html" %}
{% load staticfiles %}

{% block title %}导入图书{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="row">
				<form role="form" method="post" name="search_form">
				{% csrf_token %}
					<div class="form-group">
						<div class="col-md-6 col-md-offset-4">
						<input type="search" class="form-control" required name="query_search" id="id_query_search" autofocus/>
						</div>
						<div class="col-md-2">
						<button class="btn btn btn-primary btn-block" type="submit">查询图书</button>
						</div>
					</div>
				</form>
			</div>

			{% if list_search %}

			<div class="row">

			<form role="form" method="post" action="{% url 'import_info' %}" name="select_form" id="select_form">
			{% csrf_token %}
				<div class="form-group">
					<div class="col-md-12">
						<table class="table table-hover">
							<thead>
								<tr>
									<th><input type="checkbox" id="id_select_all"></th>
									<th>书名</th>
									<th>作者</th>
									<th>类别</th>
									<th>出版日期</th>
									<th>定价</th>
								</tr>
							</thead> 
							<tbody> 
						
								{% for book in list_search %}
								<tr>
									<td> <input type="checkbox" name="search" value="{{ book }}"/></td>
									<td>{{ book.title }}</td>
						    			<td>{{ book.author }}</td>
									<td>{{ book.category }}</td>
									<td>{{ book.pubdate }}</td>
									<td>{{ book.price }}</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
					<div class="col-md-2 col-md-offset-10">
						<button class="btn btn btn-primary btn-block" type="submit" id="form_submit">导入</button>
					</div>
				</div>

			</form>
			</div>

			{% else %}
			{% if jud %}
			<p>没有查到相关书籍！</p>
			{% endif %}
			{% endif %}

		</div>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function(){
		$("#id_select_all").click(function(){
			if (this.checked) {
				$(":checkbox").prop("checked",true);
			}else{
				$(":checkbox").prop("checked",false);
				}
				});
		});
</script>
{% endblock %}

management/templates/management/import_info.html
{% extends "management/base.html" %}
{% load staticfiles %}
{% block title %}导入信息{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
				{% if state == 'success' %}
				<div class="well">
					<h2 class="text-success text-center">导入成功</h2>
				</div>
				<ul class="pager">
					<li class="previous"><a class="text-left" href="{% url 'import_book' %}">继续导入</a></li>
					<li class="next"><a class="text-right" href="{% url 'homepage' %}">回到主页</a></li>
				</ul>

				{% else %}
				<div class="well">
					<h2 class="text-warning text-center">导入失败</h2>
				</div>
				<ul class="pager">
					<li class="next"><a class="text-right" href="{% url 'homepage' %}">回到主页</a></li>
				</ul>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

management/templates/management/signup.html
{% extends "management/base.html" %}
{% load staticfiles %}

{% block title %}注册{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
			{% if state == 'success' %}
			<div class="well">
				<h2 class="text-success text-center">注册成功！</h2>
			</div>
		   	{% elif state == 'repeat_error' %}
		    <div class="well">
				<h2 class="text-warning text-center">密码重复错误</h2>
			</div>
		    {% elif state == 'user_exist' %}
		    <div class="well">
				<h2 class="text-warning text-center">用户已存在</h2>
			</div>
		    {% elif state == 'empty' %}
			<div class="well">
				<h2 class="text-warning text-center">密码不能为空</h2>
			</div>
		    {% endif %}


		    <form method="POST" role="form" class="form-horizontal">
			{% csrf_token %}
			    <h1 class="form-signin-heading text-center">请注册</h1>

			    <div class="form-group">
					<label for="id_user_name" class="col-md-3 control-label">用户名：</label>
				   	<div class="col-md-9">
						<input type="text" class="form-control" id="id_user_name" required name="username" autofocus>
						<span class="help-block">可以包含字母和下划线</span>
				    </div>
			    </div>

			    <div class="form-group">
					<label for="id_name" class="col-md-3 control-label">昵称：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" required name="nickname" id="id_name">
				    </div>
			    </div>

			    <div class="form-group">
					<label for="id_password" class="col-md-3 control-label">密码：</label>
				   	<div class="col-md-9">
						<input type="password" class="form-control" required name="password" id="id_password">
				    </div>
			    </div>

			    <div class="form-group">
					<label for="id_repassword" class="col-md-3 control-label">重复密码：</label>
					<div class="col-md-9">
						<input type="password" class="form-control" required name="repeat_password" id="id_repassword">
				    </div>
			    </div>

			    <div class="form-group">
					<label for="id_email" class="col-md-3 control-label">电子邮件：</label>
					<div class="col-md-9">
						<input type="email" class="form-control" required name="email" id="id_email">
				    </div>
			    </div>

			    <div class="form-group">
					<div class="col-md-4 col-md-offset-4">
						<button class="btn btn btn-primary btn-block" type="submit" id="id_submit">注册</button>
					</div>
			    </div>
		    </form>
		</div>
	</div>
</div>
{% endblock %}

management/templates/management/view_pdf.html
<html>
<title>{{ pdf.name }}</title>
<body style="background-color: rgb(38,38,38); height: 100%; width: 100%; overflow: hidden; margin: 0">
	<embed height="100%" width="100%" name="view_pdf" id="id_pdf" src="{% url 'media' pdf.pdf %}" type="application/pdf"></embed>
</body>
</html>